server:
  port: 9988

spring:
  application:
    name: unknown-platform-server
  profiles:
    default: prod

management:
  endpoints:
    web:
      exposure:
        include: health,info,metrics

springdoc:
  swagger-ui:
    path: /swagger-ui/index.html
