/* eslint-disable */
/* prettier-ignore */
// @ts-nocheck
// noinspection JSUnusedGlobalSymbols
// Generated by unplugin-auto-import
// biome-ignore lint: disable
export {}
declare global {
  const AccountSummaryCard: typeof import('./components/SummaryCards/index').AccountSummaryCard
  const Activity: typeof import('react').Activity
  const AddressEditor: typeof import('./pages/settings/components/SettingsPanels').AddressEditor
  const AddressInfoForm: typeof import('./components/AddressInfoForm/index').AddressInfoForm
  const AlertCircle: typeof import('lucide-react').AlertCircle
  const App: typeof import('@h5/App').App
  const ArrowDownUp: typeof import('lucide-react').ArrowDownUp
  const ArrowLeft: typeof import('lucide-react').ArrowLeft
  const BadgeCheck: typeof import('lucide-react').BadgeCheck
  const BottomTabs: typeof import('./components/AppShell/index').BottomTabs
  const BriefcaseBusiness: typeof import('lucide-react').BriefcaseBusiness
  const BrowserRouter: typeof import('react-router-dom').BrowserRouter
  const CalendarClock: typeof import('lucide-react').CalendarClock
  const CalendarDays: typeof import('lucide-react').CalendarDays
  const CalendarPanel: typeof import('./components/ScheduleCalendar/CalendarPanel/index').CalendarPanel
  const ChatModule: typeof import('./components/ChatModule/index').ChatModule
  const CheckCircle2: typeof import('lucide-react').CheckCircle2
  const CheckoutSheet: typeof import('./components/WorkflowOverlays/index').CheckoutSheet
  const ChevronRight: typeof import('lucide-react').ChevronRight
  const CircleDollarSign: typeof import('lucide-react').CircleDollarSign
  const ClipboardCheck: typeof import('lucide-react').ClipboardCheck
  const Commission: typeof import('./pages/home/commission/index').Commission
  const CommissionAmount: typeof import('./pages/home/commission/components/CommissionAmount').CommissionAmount
  const CommissionRoute: typeof import('./pages/home/components/RouteEntries').CommissionRoute
  const CommissionTaskCard: typeof import('./pages/home/commission/components/CommissionTaskCard').CommissionTaskCard
  const CommissionTaskDetail: typeof import('./pages/home/commission/components/CommissionTaskDetail').CommissionTaskDetail
  const ConfirmAction: typeof import('./components/ConfirmAction/index').ConfirmAction
  const Crosshair: typeof import('lucide-react').Crosshair
  const DataErrorScreen: typeof import('./pages/home/auth/components/AppStateScreens/index').DataErrorScreen
  const DefaultRoute: typeof import('./pages/home/components/RouteEntries').DefaultRoute
  const EduJobBudget: typeof import('./pages/home/job/components/EduTaskCard').EduJobBudget
  const EduTaskCard: typeof import('./pages/home/job/components/EduTaskCard').EduTaskCard
  const EduTrialApplyAction: typeof import('./pages/home/job/components/EduTaskCard').EduTrialApplyAction
  const Featured: typeof import('./pages/home/shop/index').Featured
  const Filter: typeof import('lucide-react').Filter
  const FilterTags: typeof import('./pages/home/auth/components/OngoingOrders/components/FilterTags').FilterTags
  const FloatingActions: typeof import('./pages/home/auth/index').FloatingActions
  const Fragment: typeof import('react').Fragment
  const GraduationCap: typeof import('lucide-react').GraduationCap
  const Header: typeof import('./components/AppShell/index').Header
  const Heart: typeof import('lucide-react').Heart
  const Home: typeof import('lucide-react').Home
  const HomePage: typeof import('./pages/home/index').HomePage
  const HomeProvider: typeof import('./pages/home/provider').HomeProvider
  const HuntingCertification: typeof import('./pages/home/auth/components/Mine/components/HuntingCertification').HuntingCertification
  const HuntingCertificationCard: typeof import('./components/HuntingCertificationCard/index').HuntingCertificationCard
  const HuntingCertificationPrompt: typeof import('./pages/home/commission/components/HuntingCertificationPrompt').HuntingCertificationPrompt
  const HuntingProject: typeof import('./components/HuntingProject/index').HuntingProject
  const HuntingShortcut: typeof import('./pages/home/auth/components/HuntingShortcut').HuntingShortcut
  const InitialLoadingScreen: typeof import('./pages/home/auth/components/AppStateScreens/index').InitialLoadingScreen
  const JobRoute: typeof import('./pages/home/components/RouteEntries').JobRoute
  const KeyRound: typeof import('lucide-react').KeyRound
  const ListFilters: typeof import('./pages/home/edu/components/ListFilters').ListFilters
  const LogOut: typeof import('lucide-react').LogOut
  const Login: typeof import('./pages/login/index').Login
  const LoginForm: typeof import('./pages/login/components/LoginForm').LoginForm
  const LoginRegisterCard: typeof import('./pages/login/components/LoginRegisterCard').LoginRegisterCard
  const LoginRoute: typeof import('./pages/home/auth/routes').LoginRoute
  const Marketing: typeof import('./pages/marketing/index').Marketing
  const Megaphone: typeof import('lucide-react').Megaphone
  const MerchantSales: typeof import('./pages/merchant-sales/index').MerchantSales
  const MerchantSalesRoute: typeof import('./pages/home/components/RouteEntries').MerchantSalesRoute
  const MessageCircle: typeof import('lucide-react').MessageCircle
  const MessageToast: typeof import('./ui/MessageToast/index').MessageToast
  const Metric: typeof import('./components/PageWidgets/index').Metric
  const Mine: typeof import('./pages/mine/index').Mine
  const MineRoute: typeof import('./pages/home/auth/routes').MineRoute
  const MineShortcut: typeof import('./pages/home/auth/components/MineShortcut').MineShortcut
  const Modal: typeof import('./ui/Modal/index').Modal
  const Navigate: typeof import('react-router-dom').Navigate
  const NicknameEditor: typeof import('./pages/settings/components/SettingsPanels').NicknameEditor
  const OngoingHuntings: typeof import('./pages/home/auth/components/OngoingHuntings/index').OngoingHuntings
  const OngoingOrders: typeof import('./pages/home/auth/components/OngoingOrders/index').OngoingOrders
  const OngoingQuote: typeof import('./pages/home/commission/components/OngoingQuote').OngoingQuote
  const OngoingShortcut: typeof import('./pages/home/auth/components/OngoingShortcut').OngoingShortcut
  const OrderActions: typeof import('./pages/home/auth/components/OngoingOrders/components/OrderActions').OrderActions
  const OrderModuleCard: typeof import('./components/OrderModuleCard/index').OrderModuleCard
  const OrderStatus: typeof import('./pages/home/auth/components/OngoingOrders/components/OrderActions').OrderStatus
  const Orders: typeof import('./pages/orders/index').Orders
  const PackageCheck: typeof import('lucide-react').PackageCheck
  const PageShell: typeof import('./components/AppShell/index').PageShell
  const PartTime: typeof import('./pages/home/job/index').PartTime
  const PartTimeJobCard: typeof import('./pages/home/job/components/PartTimeJobCard').PartTimeJobCard
  const PasswordReset: typeof import('./pages/settings/components/SettingsPanels').PasswordReset
  const PasswordResetCard: typeof import('./pages/login/components/PasswordResetCard').PasswordResetCard
  const PhoneChange: typeof import('./pages/settings/components/SettingsPanels').PhoneChange
  const Plus: typeof import('lucide-react').Plus
  const ProductListCard: typeof import('./components/PageWidgets/index').ProductListCard
  const ProfileCompletion: typeof import('./components/WorkflowOverlays/index').ProfileCompletion
  const ProfileContextCard: typeof import('./components/AppShell/index').ProfileContextCard
  const PublishDraftConfirm: typeof import('./components/PublishInfo/DraftConfirm').PublishDraftConfirm
  const PublishInfo: typeof import('./components/PublishInfo/index').PublishInfo
  const QueryClient: typeof import('@tanstack/react-query').QueryClient
  const QueryClientProvider: typeof import('@tanstack/react-query').QueryClientProvider
  const QuickActionDock: typeof import('./pages/home/auth/components/QuickActionDock').QuickActionDock
  const RegisterForm: typeof import('./pages/login/components/RegisterForm').RegisterForm
  const RegistrationGuide: typeof import('./pages/login/components/RegistrationGuide').RegistrationGuide
  const Route: typeof import('react-router-dom').Route
  const Routes: typeof import('react-router-dom').Routes
  const ScheduleCalendar: typeof import('./components/ScheduleCalendar/index').ScheduleCalendar
  const ScrollingTicker: typeof import('./components/ScrollingTicker/index').ScrollingTicker
  const SearchToolbar: typeof import('./pages/home/job/components/SearchToolbar').SearchToolbar
  const SectionHeader: typeof import('./components/PageWidgets/index').SectionHeader
  const ServiceSettlement: typeof import('./pages/home/auth/components/OngoingOrders/components/TutorWorkflowModals').ServiceSettlement
  const Settings: typeof import('lucide-react').Settings
  const SettingsRoute: typeof import('./pages/home/auth/routes').SettingsRoute
  const SettingsView: typeof import('./pages/settings/index').SettingsView
  const ShieldCheck: typeof import('lucide-react').ShieldCheck
  const ShopRoute: typeof import('./pages/home/components/RouteEntries').ShopRoute
  const ShoppingBag: typeof import('lucide-react').ShoppingBag
  const Smartphone: typeof import('lucide-react').Smartphone
  const Store: typeof import('lucide-react').Store
  const StrictMode: typeof import('react').StrictMode
  const Suspense: typeof import('react').Suspense
  const TrialScheduleCalendar: typeof import('./components/TrialScheduleCalendar/index').TrialScheduleCalendar
  const TrialSchedulePreview: typeof import('./pages/home/auth/components/OngoingOrders/components/TutorWorkflowModals').TrialSchedulePreview
  const TrialSettlementConfirm: typeof import('./pages/home/auth/components/OngoingOrders/components/TutorWorkflowModals').TrialSettlementConfirm
  const Truck: typeof import('lucide-react').Truck
  const Tutor: typeof import('./pages/home/edu/index').Tutor
  const TutorApplicantStatus: typeof import('./db/tutorStatus').TutorApplicantStatus
  const TutorApplications: typeof import('./pages/home/edu/components/TutorApplications').TutorApplications
  const TutorCalendar: typeof import('./components/TutorCalendar/index').TutorCalendar
  const TutorCard: typeof import('./pages/home/edu/components/TutorCard').TutorCard
  const TutorCertification: typeof import('./pages/home/auth/components/Mine/components/TutorCertification').TutorCertification
  const TutorCertificationCard: typeof import('./components/TutorCertificationCard/index').TutorCertificationCard
  const TutorCertificationInfo: typeof import('./components/TutorCertificationInfo/index').TutorCertificationInfo
  const TutorDemandStatus: typeof import('./db/tutorStatus').TutorDemandStatus
  const TutorQualificationInfo: typeof import('./pages/settings/components/SettingsPanels').TutorQualificationInfo
  const TutorRoute: typeof import('./pages/home/components/RouteEntries').TutorRoute
  const TutorSubject: typeof import('./db/tutorSubject').TutorSubject
  const TutorTrialList: typeof import('./pages/home/edu/components/TutorApplications').TutorTrialList
  const TutorTrialSchedule: typeof import('./components/TutorTrialSchedule/index').TutorTrialSchedule
  const UnauthenticatedScreen: typeof import('./pages/home/auth/components/AppStateScreens/index').UnauthenticatedScreen
  const UserRound: typeof import('lucide-react').UserRound
  const Wallet: typeof import('./pages/wallet/index').Wallet
  const WalletCards: typeof import('lucide-react').WalletCards
  const WalletSummaryCard: typeof import('./components/SummaryCards/index').WalletSummaryCard
  const WorkbenchInfoCard: typeof import('./components/PageWidgets/index').WorkbenchInfoCard
  const WorkbenchQuickEntryCard: typeof import('./components/PageWidgets/index').WorkbenchQuickEntryCard
  const XCircle: typeof import('lucide-react').XCircle
  const accountStatusLabels: typeof import('@unknown/domain').accountStatusLabels
  const addressBookStorageKey: typeof import('./shared/clientPageModel').addressBookStorageKey
  const addressInfoFields: typeof import('./shared/clientPageModel').addressInfoFields
  const addressInfoTemplate: typeof import('./shared/clientPageModel').addressInfoTemplate
  const buildPublishHuntingTaskRequest: typeof import('./tools/publishInfo').buildPublishHuntingTaskRequest
  const buildPublishTutorDemandRequest: typeof import('./tools/publishInfo').buildPublishTutorDemandRequest
  const cache: typeof import('react').cache
  const cacheSignal: typeof import('react').cacheSignal
  const campusAreaOptions: typeof import('./shared/clientPageModel').campusAreaOptions
  const canConfirmHuntingQuote: typeof import('./pages/home/commission/model').canConfirmHuntingQuote
  const canCounterHuntingQuote: typeof import('./pages/home/commission/model').canCounterHuntingQuote
  const clearStoredClientAuthSession: typeof import('@unknown/api-client').clearStoredClientAuthSession
  const clearStoredPendingRegistration: typeof import('./shared/clientPageModel').clearStoredPendingRegistration
  const clientAddressToAddressBookItem: typeof import('./shared/clientPageModel').clientAddressToAddressBookItem
  const clientAddressesToAddressBookItems: typeof import('./shared/clientPageModel').clientAddressesToAddressBookItems
  const clientPrimaryTabs: typeof import('@unknown/domain').clientPrimaryTabs
  const clientPublishPlatformLabels: typeof import('@unknown/domain').clientPublishPlatformLabels
  const commissionRuleTickerItems: typeof import('./pages/home/commission/model').commissionRuleTickerItems
  const commissionSortOptions: typeof import('./pages/home/commission/model').commissionSortOptions
  const compactTutorSchedulePreviewSections: typeof import('./pages/home/auth/components/OngoingOrders/model').compactTutorSchedulePreviewSections
  const createAddressBookItem: typeof import('./shared/clientPageModel').createAddressBookItem
  const createContext: typeof import('react').createContext
  const createDefaultDaySchedule: typeof import('./components/TutorTrialSchedule/model').createDefaultDaySchedule
  const createRef: typeof import('react').createRef
  const createRoot: typeof import('react-dom/client').createRoot
  const createTutorTaskModel: typeof import('./tools/tutorTaskWorkflow').createTutorTaskModel
  const delegationRequirementTags: typeof import('./tools/publishInfo').delegationRequirementTags
  const deliveryModeLabels: typeof import('@unknown/domain').deliveryModeLabels
  const filterProducts: typeof import('./shared/clientPageModel').filterProducts
  const formatCompactWalletAmount: typeof import('./tools/wallet').formatCompactWalletAmount
  const formatCurrency: typeof import('./shared/clientPageModel').formatCurrency
  const formatTrialScheduleDate: typeof import('./components/TutorTrialSchedule/model').formatTrialScheduleDate
  const formatTutorSubjectLabels: typeof import('./shared/tutorModel').formatTutorSubjectLabels
  const formatTutorSubjects: typeof import('./shared/tutorModel').formatTutorSubjects
  const formatWalletAmount: typeof import('./tools/wallet').formatWalletAmount
  const forwardRef: typeof import('react').forwardRef
  const getChildProfileOptions: typeof import('./shared/clientPageModel').getChildProfileOptions
  const getCommissionArea: typeof import('./pages/home/commission/model').getCommissionArea
  const getCommissionDestination: typeof import('./pages/home/commission/model').getCommissionDestination
  const getCommissionPrimaryActionLabel: typeof import('./pages/home/commission/model').getCommissionPrimaryActionLabel
  const getCommissionPublishTime: typeof import('./pages/home/commission/model').getCommissionPublishTime
  const getCommissionPublisherText: typeof import('./pages/home/commission/model').getCommissionPublisherText
  const getCommissionRequirementTags: typeof import('./pages/home/commission/model').getCommissionRequirementTags
  const getCommissionTimeWeight: typeof import('./pages/home/commission/model').getCommissionTimeWeight
  const getCurrentAddressDraft: typeof import('./shared/clientPageModel').getCurrentAddressDraft
  const getDefaultDeliveryMode: typeof import('./shared/clientPageModel').getDefaultDeliveryMode
  const getDefaultPrimaryTab: typeof import('@unknown/domain').getDefaultPrimaryTab
  const getDefaultTutorScheduleDate: typeof import('./tools/tutorCalendar').getDefaultTutorScheduleDate
  const getDelegationLatestTimeLabel: typeof import('./tools/publishInfo').getDelegationLatestTimeLabel
  const getDelegationRequirementLabel: typeof import('./tools/publishInfo').getDelegationRequirementLabel
  const getDeliveryFee: typeof import('./shared/clientPageModel').getDeliveryFee
  const getEnabledPeriodSummaries: typeof import('./components/TutorTrialSchedule/model').getEnabledPeriodSummaries
  const getErrorMessage: typeof import('./tools/messageToast').getErrorMessage
  const getFilledFieldCount: typeof import('./tools/validation').getFilledFieldCount
  const getFilledProfileDraft: typeof import('./shared/clientPageModel').getFilledProfileDraft
  const getHuntingCertificationCardMode: typeof import('./components/HuntingCertificationCard/model').getHuntingCertificationCardMode
  const getHuntingCertificationDataFromDraft: typeof import('./components/HuntingCertificationCard/model').getHuntingCertificationDataFromDraft
  const getHuntingFulfillmentContact: typeof import('./pages/home/commission/model').getHuntingFulfillmentContact
  const getHuntingHistoryOrders: typeof import('./pages/home/commission/model').getHuntingHistoryOrders
  const getHuntingTaskAmountText: typeof import('./pages/home/commission/model').getHuntingTaskAmountText
  const getHuntingTaskPublishTimeText: typeof import('./pages/home/commission/model').getHuntingTaskPublishTimeText
  const getLatestLocalPublishInfoDraft: typeof import('./tools/publishInfo').getLatestLocalPublishInfoDraft
  const getLocalPublishInfoDrafts: typeof import('./tools/publishInfo').getLocalPublishInfoDrafts
  const getMessageToastSnapshot: typeof import('./tools/messageToast').getMessageToastSnapshot
  const getOngoingOrderCategory: typeof import('./pages/home/auth/components/OngoingOrders/model').getOngoingOrderCategory
  const getOngoingOrderDisplayDetail: typeof import('./pages/home/auth/components/OngoingOrders/model').getOngoingOrderDisplayDetail
  const getOrderModuleCounts: typeof import('./components/OrderModuleCard/model').getOrderModuleCounts
  const getProductFilterLabel: typeof import('./shared/clientPageModel').getProductFilterLabel
  const getProfileRequirement: typeof import('./shared/clientPageModel').getProfileRequirement
  const getProfileRequirementTemplate: typeof import('./shared/clientPageModel').getProfileRequirementTemplate
  const getPublishDestinationLabel: typeof import('./tools/publishInfo').getPublishDestinationLabel
  const getRecommendedHuntingTasks: typeof import('./pages/home/commission/model').getRecommendedHuntingTasks
  const getRoleHint: typeof import('./shared/clientPageModel').getRoleHint
  const getStoredAddressBook: typeof import('./shared/clientPageModel').getStoredAddressBook
  const getStoredClientAuthSession: typeof import('@unknown/api-client').getStoredClientAuthSession
  const getStoredPasswordCredential: typeof import('./shared/clientPageModel').getStoredPasswordCredential
  const getStoredProfileDraft: typeof import('./shared/clientPageModel').getStoredProfileDraft
  const getTabTitle: typeof import('./shared/clientPageModel').getTabTitle
  const getTrialScheduleCalendarItems: typeof import('./components/TutorTrialSchedule/model').getTrialScheduleCalendarItems
  const getTrialScheduleDateKeysFromSummary: typeof import('./components/TutorTrialSchedule/model').getTrialScheduleDateKeysFromSummary
  const getTrialSchedulePlan: typeof import('./components/TutorTrialSchedule/model').getTrialSchedulePlan
  const getTrialScheduleSummaryLines: typeof import('./components/TutorTrialSchedule/model').getTrialScheduleSummaryLines
  const getTrialScheduleValueFromSummary: typeof import('./components/TutorTrialSchedule/model').getTrialScheduleValueFromSummary
  const getTutorCalendarCells: typeof import('./tools/tutorCalendar').getTutorCalendarCells
  const getTutorCalendarTasks: typeof import('./tools/tutorCalendar').getTutorCalendarTasks
  const getTutorCardDataFromDraft: typeof import('./components/TutorCertificationCard/model').getTutorCardDataFromDraft
  const getTutorCardMode: typeof import('./components/TutorCertificationCard/model').getTutorCardMode
  const getTutorDateKey: typeof import('./tools/tutorCalendar').getTutorDateKey
  const getTutorDemandBudgetLabel: typeof import('./tools/tutorDemand').getTutorDemandBudgetLabel
  const getTutorMonthKey: typeof import('./tools/tutorCalendar').getTutorMonthKey
  const getTutorOrderSchedulePreviewConfig: typeof import('./pages/home/auth/components/OngoingOrders/model').getTutorOrderSchedulePreviewConfig
  const getTutorServiceScheduleSummaryFromOrderDetail: typeof import('./tools/tutorTrial').getTutorServiceScheduleSummaryFromOrderDetail
  const getTutorSubjectLabel: typeof import('./shared/tutorModel').getTutorSubjectLabel
  const getTutorTaskNode: typeof import('./tools/tutorTaskWorkflow').getTutorTaskNode
  const getTutorTaskStatusLabels: typeof import('./tools/tutorTaskWorkflow').getTutorTaskStatusLabels
  const getTutorTaskStatusTone: typeof import('./tools/tutorTaskWorkflow').getTutorTaskStatusTone
  const getTutorTaskStatusToneClassName: typeof import('./tools/tutorTaskWorkflow').getTutorTaskStatusToneClassName
  const getTutorTrialAvailabilitySummaryFromOrderDetail: typeof import('./tools/tutorTrial').getTutorTrialAvailabilitySummaryFromOrderDetail
  const getTutorTrialDateKeyFromLine: typeof import('./tools/tutorTrial').getTutorTrialDateKeyFromLine
  const getTutorTrialFeeSummaryFromOrderDetail: typeof import('./tools/tutorTrial').getTutorTrialFeeSummaryFromOrderDetail
  const getTutorTrialOrderDisplayDetail: typeof import('./tools/tutorTrial').getTutorTrialOrderDisplayDetail
  const getTutorTrialScheduleLines: typeof import('./tools/tutorTrial').getTutorTrialScheduleLines
  const getTutorTrialScheduleSummaryFromOrderDetail: typeof import('./tools/tutorTrial').getTutorTrialScheduleSummaryFromOrderDetail
  const getTutorTrialStatusLabel: typeof import('./tools/tutorTrial').getTutorTrialStatusLabel
  const getTutorWorkflowSuccessMessage: typeof import('./pages/home/edu/model').getTutorWorkflowSuccessMessage
  const getTutorWorkflowTargetOrder: typeof import('./pages/home/auth/components/OngoingOrders/model').getTutorWorkflowTargetOrder
  const getWalletDisplayDate: typeof import('./tools/wallet').getWalletDisplayDate
  const getWalletMonthKey: typeof import('./tools/wallet').getWalletMonthKey
  const getWalletMonthOptions: typeof import('./tools/wallet').getWalletMonthOptions
  const getWalletMonthlySummary: typeof import('./tools/wallet').getWalletMonthlySummary
  const getWalletTotalAmount: typeof import('./tools/wallet').getWalletTotalAmount
  const hasCounterQuoteAmount: typeof import('./pages/home/commission/model').hasCounterQuoteAmount
  const hasInvalidCounterQuoteAmount: typeof import('./pages/home/commission/model').hasInvalidCounterQuoteAmount
  const hasInvalidFields: typeof import('./tools/validation').hasInvalidFields
  const hasInvalidRequiredFields: typeof import('./tools/validation').hasInvalidRequiredFields
  const hasOngoingOrderActions: typeof import('./pages/home/auth/components/OngoingOrders/model').hasOngoingOrderActions
  const hasStoredPendingRegistration: typeof import('./shared/clientPageModel').hasStoredPendingRegistration
  const hasValidCounterQuoteAmount: typeof import('./pages/home/commission/model').hasValidCounterQuoteAmount
  const hideMessage: typeof import('./tools/messageToast').hideMessage
  const homeRoute: typeof import('./pages/home/routes').homeRoute
  const huntingCertificationStatusLabels: typeof import('./components/HuntingCertificationCard/model').huntingCertificationStatusLabels
  const isCommissionListVisible: typeof import('./pages/home/commission/model').isCommissionListVisible
  const isCommissionTaskLocked: typeof import('./pages/home/commission/model').isCommissionTaskLocked
  const isHuntingCancelledStatus: typeof import('./pages/home/commission/model').isHuntingCancelledStatus
  const isHuntingCompletedStatus: typeof import('./pages/home/commission/model').isHuntingCompletedStatus
  const isHuntingFulfillingStatus: typeof import('./pages/home/commission/model').isHuntingFulfillingStatus
  const isHuntingPublishedStatus: typeof import('./pages/home/commission/model').isHuntingPublishedStatus
  const isHuntingQuoteStatus: typeof import('./pages/home/commission/model').isHuntingQuoteStatus
  const isHuntingQuoteWaitingHunter: typeof import('./pages/home/commission/model').isHuntingQuoteWaitingHunter
  const isHuntingQuoteWaitingPublisher: typeof import('./pages/home/commission/model').isHuntingQuoteWaitingPublisher
  const isHuntingTaskPublishType: typeof import('./tools/publishInfo').isHuntingTaskPublishType
  const isNegotiableAmount: typeof import('./tools/publishInfo').isNegotiableAmount
  const isNegotiatingHuntingQuote: typeof import('./pages/home/commission/model').isNegotiatingHuntingQuote
  const isParentTutorServiceSchedulePending: typeof import('./pages/home/auth/components/OngoingOrders/model').isParentTutorServiceSchedulePending
  const isPositiveAmount: typeof import('./tools/publishInfo').isPositiveAmount
  const isQuoteLockedForPublisher: typeof import('./pages/home/commission/model').isQuoteLockedForPublisher
  const isTutorApplicationListStatus: typeof import('./tools/tutorTrial').isTutorApplicationListStatus
  const isTutorApplicationPendingStatus: typeof import('./tools/tutorTrial').isTutorApplicationPendingStatus
  const isTutorDemand: typeof import('./hooks/useClientWorkspaceViewModel').isTutorDemand
  const isTutorFormalServiceStatus: typeof import('./tools/tutorTrial').isTutorFormalServiceStatus
  const isTutorPublishType: typeof import('./tools/publishInfo').isTutorPublishType
  const isTutorServiceConfirmingStatus: typeof import('./tools/tutorTrial').isTutorServiceConfirmingStatus
  const isTutorServiceEndConfirmingStatus: typeof import('./tools/tutorTrial').isTutorServiceEndConfirmingStatus
  const isTutorServiceInvalidStatus: typeof import('./tools/tutorTrial').isTutorServiceInvalidStatus
  const isTutorServiceScheduleConfirmingStatus: typeof import('./tools/tutorTrial').isTutorServiceScheduleConfirmingStatus
  const isTutorServiceSchedulePendingStatus: typeof import('./tools/tutorTrial').isTutorServiceSchedulePendingStatus
  const isTutorSettlementStatus: typeof import('./tools/tutorTrial').isTutorSettlementStatus
  const isTutorTerminalStatus: typeof import('./tools/tutorTrial').isTutorTerminalStatus
  const isTutorTrialConfirmingStatus: typeof import('./tools/tutorTrial').isTutorTrialConfirmingStatus
  const isTutorTrialEndConfirmingStatus: typeof import('./tools/tutorTrial').isTutorTrialEndConfirmingStatus
  const isTutorTrialListStatus: typeof import('./tools/tutorTrial').isTutorTrialListStatus
  const isTutorTrialResultProcessingStatus: typeof import('./tools/tutorTrial').isTutorTrialResultProcessingStatus
  const isTutorTrialSettledServicePendingStatus: typeof import('./tools/tutorTrial').isTutorTrialSettledServicePendingStatus
  const isTutorTrialingStatus: typeof import('./tools/tutorTrial').isTutorTrialingStatus
  const isTutorWageAmountRequired: typeof import('./tools/publishInfo').isTutorWageAmountRequired
  const jobFilters: typeof import('./shared/clientPageModel').jobFilters
  const lazy: typeof import('react').lazy
  const localAuthCode: typeof import('./tools/localAuth').localAuthCode
  const localPasswordMinLength: typeof import('./tools/localAuth').localPasswordMinLength
  const memo: typeof import('react').memo
  const merchantRegistrationBusinessFields: typeof import('./shared/clientPageModel').merchantRegistrationBusinessFields
  const mergeHuntingTasks: typeof import('./pages/home/commission/model').mergeHuntingTasks
  const messageToastApi: typeof import('./tools/messageToast').messageToastApi
  const messageToastMeta: typeof import('./tools/messageToast').messageToastMeta
  const mineEntryLabels: typeof import('@unknown/domain').mineEntryLabels
  const normalizeAddressBookItems: typeof import('./shared/clientPageModel').normalizeAddressBookItems
  const normalizeByKey: typeof import('./tools/validation').normalizeByKey
  const normalizeTutorWageMode: typeof import('./tools/publishInfo').normalizeTutorWageMode
  const parentChildInfoFields: typeof import('./shared/clientPageModel').parentChildInfoFields
  const parentRegistrationAddressFields: typeof import('./shared/clientPageModel').parentRegistrationAddressFields
  const parentRegistrationProfileTemplate: typeof import('./shared/clientPageModel').parentRegistrationProfileTemplate
  const parseTutorSubjectLevelItems: typeof import('./components/TutorCertificationCard/model').parseTutorSubjectLevelItems
  const parseTutorSubjects: typeof import('./shared/tutorModel').parseTutorSubjects
  const parseTutorTrialSchedule: typeof import('./tools/tutorTrial').parseTutorTrialSchedule
  const parseWalletBucketAmount: typeof import('./tools/wallet').parseWalletBucketAmount
  const parseWalletRecordAmount: typeof import('./tools/wallet').parseWalletRecordAmount
  const passwordCredentialStorageKey: typeof import('./shared/clientPageModel').passwordCredentialStorageKey
  const paymentMethodLabels: typeof import('@unknown/domain').paymentMethodLabels
  const pendingRegistrationStorageKey: typeof import('./shared/clientPageModel').pendingRegistrationStorageKey
  const productFilters: typeof import('./shared/clientPageModel').productFilters
  const profileDraftStorageKey: typeof import('./shared/clientPageModel').profileDraftStorageKey
  const profileDraftToClientAddressRequest: typeof import('./shared/clientPageModel').profileDraftToClientAddressRequest
  const profileRequirementTemplates: typeof import('./shared/clientPageModel').profileRequirementTemplates
  const registrationProfileTemplates: typeof import('./shared/clientPageModel').registrationProfileTemplates
  const roleLabels: typeof import('@unknown/domain').roleLabels
  const roles: typeof import('./shared/clientPageModel').roles
  const saveLocalPasswordCredential: typeof import('./tools/localAuth').saveLocalPasswordCredential
  const saveLocalPublishInfoDraft: typeof import('./tools/publishInfo').saveLocalPublishInfoDraft
  const setStoredAddressBook: typeof import('./shared/clientPageModel').setStoredAddressBook
  const setStoredClientAuthSession: typeof import('@unknown/api-client').setStoredClientAuthSession
  const setStoredPasswordCredential: typeof import('./shared/clientPageModel').setStoredPasswordCredential
  const setStoredPendingRegistration: typeof import('./shared/clientPageModel').setStoredPendingRegistration
  const setStoredProfileDraft: typeof import('./shared/clientPageModel').setStoredProfileDraft
  const showMessage: typeof import('./tools/messageToast').showMessage
  const startTransition: typeof import('react').startTransition
  const stringifyTutorSubjectLevelItems: typeof import('./components/TutorCertificationCard/model').stringifyTutorSubjectLevelItems
  const subscribeMessageToast: typeof import('./tools/messageToast').subscribeMessageToast
  const tabIcons: typeof import('./shared/clientPageModel').tabIcons
  const trialSchedulePeriods: typeof import('./components/TutorTrialSchedule/model').trialSchedulePeriods
  const tutorApplicantStatusLabel: typeof import('./db/tutorStatus').tutorApplicantStatusLabel
  const tutorCertificationStatusLabels: typeof import('./components/TutorCertificationCard/model').tutorCertificationStatusLabels
  const tutorDemandStatusLabel: typeof import('./db/tutorStatus').tutorDemandStatusLabel
  const tutorGradeOptions: typeof import('./components/TutorCertificationCard/model').tutorGradeOptions
  const tutorLevelOptions: typeof import('./components/TutorCertificationCard/model').tutorLevelOptions
  const tutorServiceAvailabilityDetailMarker: typeof import('./tools/tutorTrial').tutorServiceAvailabilityDetailMarker
  const tutorServiceFeeDetailMarker: typeof import('./tools/tutorTrial').tutorServiceFeeDetailMarker
  const tutorServiceScheduleDetailMarker: typeof import('./tools/tutorTrial').tutorServiceScheduleDetailMarker
  const tutorSubjectLabel: typeof import('./db/tutorSubject').tutorSubjectLabel
  const tutorSubjectOptions: typeof import('./shared/tutorModel').tutorSubjectOptions
  const tutorTrialAvailabilityDetailMarker: typeof import('./tools/tutorTrial').tutorTrialAvailabilityDetailMarker
  const tutorTrialFeeDetailMarker: typeof import('./tools/tutorTrial').tutorTrialFeeDetailMarker
  const tutorTrialScheduleDetailMarker: typeof import('./tools/tutorTrial').tutorTrialScheduleDetailMarker
  const tutorWageModeOptions: typeof import('./tools/publishInfo').tutorWageModeOptions
  const use: typeof import('react').use
  const useActionState: typeof import('react').useActionState
  const useApplyTutorTrial: typeof import('@unknown/hooks').useApplyTutorTrial
  const useAuthSessionFlow: typeof import('./hooks/useAuthSessionFlow').useAuthSessionFlow
  const useCallback: typeof import('react').useCallback
  const useCertificationInfoFlow: typeof import('./hooks/useCertificationInfoFlow').useCertificationInfoFlow
  const useChatConversations: typeof import('@unknown/hooks').useChatConversations
  const useChatMessages: typeof import('@unknown/hooks').useChatMessages
  const useChatQuickActions: typeof import('@unknown/hooks').useChatQuickActions
  const useClientAddresses: typeof import('@unknown/hooks').useClientAddresses
  const useClientBusinessMutations: typeof import('./hooks/useClientBusinessMutations').useClientBusinessMutations
  const useClientDataQueries: typeof import('./hooks/useClientDataQueries').useClientDataQueries
  const useClientHome: typeof import('@unknown/hooks').useClientHome
  const useClientLogin: typeof import('@unknown/hooks').useClientLogin
  const useClientRegister: typeof import('@unknown/hooks').useClientRegister
  const useClientWorkspace: typeof import('@unknown/hooks').useClientWorkspace
  const useClientWorkspaceViewModel: typeof import('./hooks/useClientWorkspaceViewModel').useClientWorkspaceViewModel
  const useCommissionActions: typeof import('./pages/home/commission/hooks/useCommissionActions').useCommissionActions
  const useCommissionList: typeof import('./pages/home/commission/hooks/useCommissionList').useCommissionList
  const useCommissionTaskFlow: typeof import('./pages/home/commission/hooks/useCommissionTaskFlow').useCommissionTaskFlow
  const useConfirmAction: typeof import('./hooks/useConfirmAction').useConfirmAction
  const useContext: typeof import('react').useContext
  const useCreateChatConversation: typeof import('@unknown/hooks').useCreateChatConversation
  const useCreateChatQuickAction: typeof import('@unknown/hooks').useCreateChatQuickAction
  const useCreateClientAddress: typeof import('@unknown/hooks').useCreateClientAddress
  const useCreateHuntingProject: typeof import('@unknown/hooks').useCreateHuntingProject
  const useDebugValue: typeof import('react').useDebugValue
  const useDeferredValue: typeof import('react').useDeferredValue
  const useDeleteClientAddress: typeof import('@unknown/hooks').useDeleteClientAddress
  const useEffect: typeof import('react').useEffect
  const useEffectEvent: typeof import('react').useEffectEvent
  const useFloatingActionsProps: typeof import('./pages/home/auth/hooks/useFloatingActionsProps').useFloatingActionsProps
  const useHomeRuntimeContext: typeof import('./pages/home/provider').useHomeRuntimeContext
  const useHuntingShortcutFlow: typeof import('./hooks/useHuntingShortcutFlow').useHuntingShortcutFlow
  const useHuntingTaskActions: typeof import('./pages/home/commission/hooks/useHuntingTaskActions').useHuntingTaskActions
  const useId: typeof import('react').useId
  const useImperativeHandle: typeof import('react').useImperativeHandle
  const useInsertionEffect: typeof import('react').useInsertionEffect
  const useLayoutEffect: typeof import('react').useLayoutEffect
  const useLocation: typeof import('react-router-dom').useLocation
  const useMemo: typeof import('react').useMemo
  const useNavigate: typeof import('react-router-dom').useNavigate
  const useOngoingQuoteFlow: typeof import('./pages/home/commission/hooks/useOngoingQuoteFlow').useOngoingQuoteFlow
  const useOptimistic: typeof import('react').useOptimistic
  const useOverlayController: typeof import('./hooks/useOverlayController').useOverlayController
  const usePrimaryTabWorkspaceRefresh: typeof import('./hooks/usePrimaryTabWorkspaceRefresh').usePrimaryTabWorkspaceRefresh
  const useProducts: typeof import('@unknown/hooks').useProducts
  const useProfileCompletionFlow: typeof import('./hooks/useProfileCompletionFlow').useProfileCompletionFlow
  const usePublishHuntingTask: typeof import('@unknown/hooks').usePublishHuntingTask
  const usePublishTutorDemand: typeof import('@unknown/hooks').usePublishTutorDemand
  const usePurchaseProduct: typeof import('@unknown/hooks').usePurchaseProduct
  const useReducer: typeof import('react').useReducer
  const useRef: typeof import('react').useRef
  const useResetClientPassword: typeof import('@unknown/hooks').useResetClientPassword
  const useRootNavigation: typeof import('./hooks/useRootNavigation').useRootNavigation
  const useSendChatMessage: typeof import('@unknown/hooks').useSendChatMessage
  const useState: typeof import('react').useState
  const useSyncExternalStore: typeof import('react').useSyncExternalStore
  const useTransition: typeof import('react').useTransition
  const useTutorTrialActions: typeof import('./pages/home/edu/hooks/useTutorTrialActions').useTutorTrialActions
  const useUpdateClientAddress: typeof import('@unknown/hooks').useUpdateClientAddress
  const useUpdateClientNickname: typeof import('@unknown/hooks').useUpdateClientNickname
  const useUpdateTutorExposure: typeof import('@unknown/hooks').useUpdateTutorExposure
  const useUseClientAddress: typeof import('@unknown/hooks').useUseClientAddress
  const validateByKey: typeof import('./tools/validation').validateByKey
  const verifyLocalPasswordCredential: typeof import('./tools/localAuth').verifyLocalPasswordCredential
}
// for type re-export
declare global {
  // @ts-ignore
  export type { ChatModuleProps } from './components/ChatModule/index'
  import('./components/ChatModule/index')
  // @ts-ignore
  export type { ConfirmActionProps } from './components/ConfirmAction/index'
  import('./components/ConfirmAction/index')
  // @ts-ignore
  export type { HuntingCertificationCardProps } from './components/HuntingCertificationCard/index'
  import('./components/HuntingCertificationCard/index')
  // @ts-ignore
  export type { HuntingCertificationCardMode, HuntingCertificationCardData, HuntingCertificationStatus } from './components/HuntingCertificationCard/model'
  import('./components/HuntingCertificationCard/model')
  // @ts-ignore
  export type { OrderModuleCardVariant, OrderModuleCardProps } from './components/OrderModuleCard/index'
  import('./components/OrderModuleCard/index')
  // @ts-ignore
  export type { OrderModuleCounts } from './components/OrderModuleCard/model'
  import('./components/OrderModuleCard/model')
  // @ts-ignore
  export type { PublishDraftConfirmProps } from './components/PublishInfo/DraftConfirm'
  import('./components/PublishInfo/DraftConfirm')
  // @ts-ignore
  export type { PublishInfoProps } from './components/PublishInfo/index'
  import('./components/PublishInfo/index')
  // @ts-ignore
  export type { CalendarPanelMode, CalendarPanelProps } from './components/ScheduleCalendar/CalendarPanel/index'
  import('./components/ScheduleCalendar/CalendarPanel/index')
  // @ts-ignore
  export type { ScrollingTickerDirection, ScrollingTickerProps } from './components/ScrollingTicker/index'
  import('./components/ScrollingTicker/index')
  // @ts-ignore
  export type { SummaryCardVariant, AccountSummaryCardProps, WalletSummaryCardProps } from './components/SummaryCards/index'
  import('./components/SummaryCards/index')
  // @ts-ignore
  export type { TrialScheduleCalendarPeriod, TrialScheduleCalendarMode, TrialScheduleCalendarItem, TrialScheduleCalendarProps } from './components/TrialScheduleCalendar/index'
  import('./components/TrialScheduleCalendar/index')
  // @ts-ignore
  export type { TutorCalendarTask, TutorCalendarProps } from './components/TutorCalendar/index'
  import('./components/TutorCalendar/index')
  // @ts-ignore
  export type { TutorCertificationCardProps } from './components/TutorCertificationCard/index'
  import('./components/TutorCertificationCard/index')
  // @ts-ignore
  export type { TutorCardMode, TutorSubjectLevelItem, TutorCardData, TutorCertificationStatus } from './components/TutorCertificationCard/model'
  import('./components/TutorCertificationCard/model')
  // @ts-ignore
  export type { TutorCertificationInfoSaveMode, TutorCertificationInfoProps } from './components/TutorCertificationInfo/index'
  import('./components/TutorCertificationInfo/index')
  // @ts-ignore
  export type { TrialSchedulePeriodKey, TrialSchedulePeriodConfig, TrialSchedulePeriodState, TrialScheduleDraft, TrialSchedulePlan, TrialScheduleValue, TrialScheduleCalendarMarker } from './components/TutorTrialSchedule/model'
  import('./components/TutorTrialSchedule/model')
  // @ts-ignore
  export type { TutorDemandStatus, TutorApplicantStatus } from './db/tutorStatus'
  import('./db/tutorStatus')
  // @ts-ignore
  export type { TutorSubject } from './db/tutorSubject'
  import('./db/tutorSubject')
  // @ts-ignore
  export type { ConfirmActionConfig } from './hooks/useConfirmAction'
  import('./hooks/useConfirmAction')
  // @ts-ignore
  export type { OngoingOrderFilter, TutorServiceAvailabilityAction, TutorOrderSchedulePreviewConfig, TutorSchedulePreviewSection, OngoingOrderActionHandlers } from './pages/home/auth/components/OngoingOrders/model'
  import('./pages/home/auth/components/OngoingOrders/model')
  // @ts-ignore
  export type { CommissionSortMode, CommissionToolbarPanel } from './pages/home/commission/model'
  import('./pages/home/commission/model')
  // @ts-ignore
  export type { EduTaskCardJob } from './pages/home/job/components/EduTaskCard'
  import('./pages/home/job/components/EduTaskCard')
  // @ts-ignore
  export type { AddressEditorMode, PhoneChangeDraft, PasswordResetDraft } from './pages/settings/components/SettingsPanels'
  import('./pages/settings/components/SettingsPanels')
  // @ts-ignore
  export type { StoredPasswordCredential, PasswordCredentialStore, PendingRegistrationRecord, PendingRegistrationStore } from './shared/clientPageModel'
  import('./shared/clientPageModel')
  // @ts-ignore
  export type { PublishInfoType, DelegationAmountMode, PublishInfoDraft, LocalPublishInfoDraft } from './tools/publishInfo'
  import('./tools/publishInfo')
  // @ts-ignore
  export type { TutorTaskNode, TutorTaskAction, TutorTaskStatusTone, TutorTaskModel } from './tools/tutorTaskWorkflow'
  import('./tools/tutorTaskWorkflow')
  // @ts-ignore
  export type { TutorTrialScheduleLine } from './tools/tutorTrial'
  import('./tools/tutorTrial')
  // @ts-ignore
  export type { ValidationResult, ValidationContext } from './tools/validation'
  import('./tools/validation')
  // @ts-ignore
  export type { WalletMonthOption, WalletMonthlySummary } from './tools/wallet'
  import('./tools/wallet')
  // @ts-ignore
  export type { PageSurface, AuthMode, LoginCredentialMode, ProductFilter, JobFilter } from './types/app'
  import('./types/app')
  // @ts-ignore
  export type { H5RuntimeGlobals, ApiEnvelope, PasswordResetResult, LoginProps, LoginFormProps, RegisterFormProps, LoginRegisterCardProps, PasswordResetCardProps, RegistrationGuideProps } from './types/auth'
  import('./types/auth')
  // @ts-ignore
  export type { CommissionProps, UseHuntingTaskActionsOptions } from './types/commission'
  import('./types/commission')
  // @ts-ignore
  export type { HuntingShortcutProps, MineProps, MineShortcutProps, OngoingShortcutProps, OngoingHuntingFulfillmentAction, OngoingOrdersProps, FloatingActionsModel, FloatingActionsProps, UseFloatingActionsPropsOptions } from './types/floating-actions'
  import('./types/floating-actions')
  // @ts-ignore
  export type { HuntingAreaInputMode, HuntingProjectStop, HuntingProjectDraft, HuntingProjectProps } from './types/hunting-project'
  import('./types/hunting-project')
  // @ts-ignore
  export type { MessageToastType, MessageToastState, MessageToastOptions } from './types/message-toast'
  import('./types/message-toast')
  // @ts-ignore
  export type { OverlayLane, TutorOverlayType, PublishOverlayType, GlobalOverlayType, GlobalOverlayEntry, OverlayState, OverlayAction, OverlayActions, OverlayProviderProps, CheckoutState, CheckoutOverlayState, CheckoutOverlayActions, CheckoutTriggerContextValue, CheckoutProviderProps, TutorOverlayActions, TutorOverlayState, TutorOverlayHostContextValue, TutorOverlayProviderProps } from './types/overlay'
  import('./types/overlay')
  // @ts-ignore
  export type { ProfileRequirementField, ProfileRequirementTemplate, ProfileRequirement, ProfileDraftState, RegistrationProfileField, RegistrationProfileTemplate, RegistrationProfileDraft, AddressInfoFormMode, AddressInfoPreviewVariant, AddressBookItem, AddressInfoFormProps } from './types/profile'
  import('./types/profile')
  // @ts-ignore
  export type { PublishOverlayDraftState, PublishOverlayDraftAction, PublishOverlayActions, PublishOverlayHostContextValue, PublishOverlayProviderProps } from './types/publish'
  import('./types/publish')
  // @ts-ignore
  export type { ChildProfileOption, TutorTrialJob, TutorApplicationCandidate, ConfirmTutorTrialPayload, CompleteTutorTrialEndPayload, TutorWorkflowActionPayload, TutorWorkflowAction, TutorWorkflowActionRequest } from './types/tutor-workflow'
  import('./types/tutor-workflow')
  // @ts-ignore
  export type { ModalProps } from './ui/Modal/index'
  import('./ui/Modal/index')
}
