/* eslint-disable */
/* prettier-ignore */
// @ts-nocheck
// noinspection JSUnusedGlobalSymbols
// Generated by unplugin-auto-import
// biome-ignore lint: disable
export {}
declare global {
  const AccountSummaryCard: typeof import('./components/SummaryCards/index').AccountSummaryCard
  const Activity: typeof import('react').Activity
  const AddressEditorDialog: typeof import('./pages/Settings/components/SettingsDialogs').AddressEditorDialog
  const AddressInfoForm: typeof import('./components/AddressInfoForm/index').AddressInfoForm
  const AlertCircle: typeof import('lucide-react').AlertCircle
  const App: typeof import('@h5/App').App
  const ArrowDownUp: typeof import('lucide-react').ArrowDownUp
  const ArrowLeft: typeof import('lucide-react').ArrowLeft
  const BadgeCheck: typeof import('lucide-react').BadgeCheck
  const BottomTabs: typeof import('./components/AppShell/index').BottomTabs
  const BriefcaseBusiness: typeof import('lucide-react').BriefcaseBusiness
  const BrowserRouter: typeof import('react-router-dom').BrowserRouter
  const CalendarClock: typeof import('lucide-react').CalendarClock
  const ChatModule: typeof import('./components/ChatModule/index').ChatModule
  const CheckCircle2: typeof import('lucide-react').CheckCircle2
  const CheckoutSheet: typeof import('./components/WorkflowDialogs/index').CheckoutSheet
  const ChevronRight: typeof import('lucide-react').ChevronRight
  const CircleDollarSign: typeof import('lucide-react').CircleDollarSign
  const ClipboardCheck: typeof import('lucide-react').ClipboardCheck
  const Crosshair: typeof import('lucide-react').Crosshair
  const Delegation: typeof import('./pages/Delegation/index').Delegation
  const DelegationAmountDialog: typeof import('./pages/Delegation/components/DelegationAmountDialog').DelegationAmountDialog
  const DelegationTaskCard: typeof import('./pages/Delegation/components/DelegationTaskCard').DelegationTaskCard
  const DelegationTaskDetailDialog: typeof import('./pages/Delegation/components/DelegationTaskDetailDialog').DelegationTaskDetailDialog
  const Featured: typeof import('./pages/Featured/index').Featured
  const Filter: typeof import('lucide-react').Filter
  const Fragment: typeof import('react').Fragment
  const GlobalStoreContext: typeof import('./store/global').GlobalStoreContext
  const GlobalStoreProvider: typeof import('./store/GlobalStoreProvider').GlobalStoreProvider
  const GraduationCap: typeof import('lucide-react').GraduationCap
  const Header: typeof import('./components/AppShell/index').Header
  const Heart: typeof import('lucide-react').Heart
  const Home: typeof import('lucide-react').Home
  const HuntingCertification: typeof import('./pages/HuntingCertification/index').HuntingCertification
  const HuntingCertificationCard: typeof import('./components/HuntingCertificationCard/index').HuntingCertificationCard
  const HuntingCertificationPromptDialog: typeof import('./pages/Delegation/components/HuntingCertificationPromptDialog').HuntingCertificationPromptDialog
  const HuntingProjectDialog: typeof import('./components/HuntingProjectDialog/index').HuntingProjectDialog
  const HuntingRecommendationDialog: typeof import('./pages/Delegation/components/HuntingRecommendationDialog').HuntingRecommendationDialog
  const KeyRound: typeof import('lucide-react').KeyRound
  const LogOut: typeof import('lucide-react').LogOut
  const Login: typeof import('./pages/Login/index').Login
  const LoginForm: typeof import('./pages/Login/components/LoginForm').LoginForm
  const LoginRegisterCard: typeof import('./pages/Login/components/LoginRegisterCard').LoginRegisterCard
  const Marketing: typeof import('./pages/Marketing/index').Marketing
  const Megaphone: typeof import('lucide-react').Megaphone
  const MerchantSales: typeof import('./pages/MerchantSales/index').MerchantSales
  const MessageCircle: typeof import('lucide-react').MessageCircle
  const MessageToast: typeof import('./components/MessageToast/index').MessageToast
  const Metric: typeof import('./components/PageWidgets/index').Metric
  const Mine: typeof import('./pages/Mine/index').Mine
  const MinePopover: typeof import('./components/AppShell/index').MinePopover
  const Navigate: typeof import('react-router-dom').Navigate
  const NicknameEditorDialog: typeof import('./pages/Settings/components/SettingsDialogs').NicknameEditorDialog
  const OngoingOrdersDialog: typeof import('./components/WorkflowDialogs/index').OngoingOrdersDialog
  const OngoingOrdersList: typeof import('./components/OngoingOrdersList/index').OngoingOrdersList
  const OngoingQuoteDialog: typeof import('./pages/Delegation/components/OngoingQuoteDialog').OngoingQuoteDialog
  const OrderModuleCard: typeof import('./components/OrderModuleCard/index').OrderModuleCard
  const Orders: typeof import('./pages/Orders/index').Orders
  const PackageCheck: typeof import('lucide-react').PackageCheck
  const PageShell: typeof import('./components/AppShell/index').PageShell
  const PartTime: typeof import('./pages/PartTime/index').PartTime
  const PartTimeJobCard: typeof import('./components/PageWidgets/index').PartTimeJobCard
  const PasswordResetCard: typeof import('./pages/Login/components/PasswordResetCard').PasswordResetCard
  const PasswordResetDialog: typeof import('./pages/Settings/components/SettingsDialogs').PasswordResetDialog
  const PhoneChangeDialog: typeof import('./pages/Settings/components/SettingsDialogs').PhoneChangeDialog
  const Plus: typeof import('lucide-react').Plus
  const ProductListCard: typeof import('./components/PageWidgets/index').ProductListCard
  const ProfileCompletionDialog: typeof import('./components/WorkflowDialogs/index').ProfileCompletionDialog
  const ProfileContextCard: typeof import('./components/AppShell/index').ProfileContextCard
  const PublishInfoDialog: typeof import('./components/PublishInfoDialog/index').PublishInfoDialog
  const QueryClient: typeof import('@tanstack/react-query').QueryClient
  const QueryClientProvider: typeof import('@tanstack/react-query').QueryClientProvider
  const RegisterForm: typeof import('./pages/Login/components/RegisterForm').RegisterForm
  const RegistrationGuide: typeof import('./pages/Login/components/RegistrationGuide').RegistrationGuide
  const Route: typeof import('react-router-dom').Route
  const Routes: typeof import('react-router-dom').Routes
  const ScrollingTicker: typeof import('./components/ScrollingTicker/index').ScrollingTicker
  const SectionHeader: typeof import('./components/PageWidgets/index').SectionHeader
  const Settings: typeof import('lucide-react').Settings
  const SettingsView: typeof import('./pages/Settings/index').SettingsView
  const ShieldCheck: typeof import('lucide-react').ShieldCheck
  const ShoppingBag: typeof import('lucide-react').ShoppingBag
  const Smartphone: typeof import('lucide-react').Smartphone
  const Store: typeof import('lucide-react').Store
  const StrictMode: typeof import('react').StrictMode
  const Suspense: typeof import('react').Suspense
  const Truck: typeof import('lucide-react').Truck
  const Tutor: typeof import('./pages/Tutor/index').Tutor
  const TutorApplicationsDialog: typeof import('./pages/Tutor/components/TutorApplicationsDialog').TutorApplicationsDialog
  const TutorCalendarDialog: typeof import('./components/TutorCalendar/index').TutorCalendarDialog
  const TutorCard: typeof import('./components/TutorCard/index').TutorCard
  const TutorCertification: typeof import('./pages/Tutor/TutorCertification').TutorCertification
  const TutorCertificationInfoDialog: typeof import('./components/TutorCertificationInfoDialog/index').TutorCertificationInfoDialog
  const TutorQualificationInfoDialog: typeof import('./pages/Settings/components/SettingsDialogs').TutorQualificationInfoDialog
  const TutorTrialJobCard: typeof import('./components/PageWidgets/index').TutorTrialJobCard
  const UserRound: typeof import('lucide-react').UserRound
  const Wallet: typeof import('./pages/Wallet/index').Wallet
  const WalletCards: typeof import('lucide-react').WalletCards
  const WalletSummaryCard: typeof import('./components/SummaryCards/index').WalletSummaryCard
  const WorkbenchInfoCard: typeof import('./components/PageWidgets/index').WorkbenchInfoCard
  const WorkbenchQuickEntryCard: typeof import('./components/PageWidgets/index').WorkbenchQuickEntryCard
  const XCircle: typeof import('lucide-react').XCircle
  const accountStatusLabels: typeof import('@unknown/domain').accountStatusLabels
  const addressBookStorageKey: typeof import('./shared/clientPageModel').addressBookStorageKey
  const addressInfoFields: typeof import('./shared/clientPageModel').addressInfoFields
  const addressInfoTemplate: typeof import('./shared/clientPageModel').addressInfoTemplate
  const buildPublishHuntingTaskRequest: typeof import('./tools/publishInfo').buildPublishHuntingTaskRequest
  const buildPublishTutorDemandRequest: typeof import('./tools/publishInfo').buildPublishTutorDemandRequest
  const cache: typeof import('react').cache
  const cacheSignal: typeof import('react').cacheSignal
  const campusAreaOptions: typeof import('./shared/clientPageModel').campusAreaOptions
  const canConfirmHuntingQuote: typeof import('./pages/Delegation/model').canConfirmHuntingQuote
  const canCounterHuntingQuote: typeof import('./pages/Delegation/model').canCounterHuntingQuote
  const clearStoredClientAuthSession: typeof import('@unknown/api-client').clearStoredClientAuthSession
  const clearStoredPendingRegistration: typeof import('./shared/clientPageModel').clearStoredPendingRegistration
  const clientAddressToAddressBookItem: typeof import('./shared/clientPageModel').clientAddressToAddressBookItem
  const clientAddressesToAddressBookItems: typeof import('./shared/clientPageModel').clientAddressesToAddressBookItems
  const clientPrimaryTabs: typeof import('@unknown/domain').clientPrimaryTabs
  const clientPublishPlatformLabels: typeof import('@unknown/domain').clientPublishPlatformLabels
  const createAddressBookItem: typeof import('./shared/clientPageModel').createAddressBookItem
  const createContext: typeof import('react').createContext
  const createGlobalStore: typeof import('./store/global').createGlobalStore
  const createRef: typeof import('react').createRef
  const createRoot: typeof import('react-dom/client').createRoot
  const delegationRequirementTags: typeof import('./tools/publishInfo').delegationRequirementTags
  const delegationRuleTickerItems: typeof import('./pages/Delegation/model').delegationRuleTickerItems
  const delegationSortOptions: typeof import('./pages/Delegation/model').delegationSortOptions
  const deliveryModeLabels: typeof import('@unknown/domain').deliveryModeLabels
  const filterProducts: typeof import('./shared/clientPageModel').filterProducts
  const formatCompactWalletAmount: typeof import('./tools/wallet').formatCompactWalletAmount
  const formatCurrency: typeof import('./shared/clientPageModel').formatCurrency
  const formatTutorSubjects: typeof import('./shared/tutorModel').formatTutorSubjects
  const formatWalletAmount: typeof import('./tools/wallet').formatWalletAmount
  const forwardRef: typeof import('react').forwardRef
  const getChildProfileOptions: typeof import('./shared/clientPageModel').getChildProfileOptions
  const getCurrentAddressDraft: typeof import('./shared/clientPageModel').getCurrentAddressDraft
  const getDefaultDeliveryMode: typeof import('./shared/clientPageModel').getDefaultDeliveryMode
  const getDefaultPrimaryTab: typeof import('@unknown/domain').getDefaultPrimaryTab
  const getDefaultRouteForRole: typeof import('./shared/clientPageModel').getDefaultRouteForRole
  const getDelegationAmountText: typeof import('./pages/Delegation/model').getDelegationAmountText
  const getDelegationArea: typeof import('./pages/Delegation/model').getDelegationArea
  const getDelegationDestination: typeof import('./pages/Delegation/model').getDelegationDestination
  const getDelegationLatestTimeLabel: typeof import('./tools/publishInfo').getDelegationLatestTimeLabel
  const getDelegationPrimaryActionLabel: typeof import('./pages/Delegation/model').getDelegationPrimaryActionLabel
  const getDelegationPublishTime: typeof import('./pages/Delegation/model').getDelegationPublishTime
  const getDelegationPublisherText: typeof import('./pages/Delegation/model').getDelegationPublisherText
  const getDelegationRequirementLabel: typeof import('./tools/publishInfo').getDelegationRequirementLabel
  const getDelegationRequirementTags: typeof import('./pages/Delegation/model').getDelegationRequirementTags
  const getDelegationTimeWeight: typeof import('./pages/Delegation/model').getDelegationTimeWeight
  const getDeliveryFee: typeof import('./shared/clientPageModel').getDeliveryFee
  const getErrorMessage: typeof import('./tools/messageToast').getErrorMessage
  const getFilledFieldCount: typeof import('./tools/validation').getFilledFieldCount
  const getFilledProfileDraft: typeof import('./shared/clientPageModel').getFilledProfileDraft
  const getHuntingCertificationCardMode: typeof import('./components/HuntingCertificationCard/model').getHuntingCertificationCardMode
  const getHuntingCertificationDataFromDraft: typeof import('./components/HuntingCertificationCard/model').getHuntingCertificationDataFromDraft
  const getHuntingFulfillmentContact: typeof import('./pages/Delegation/model').getHuntingFulfillmentContact
  const getHuntingHistoryOrders: typeof import('./pages/Delegation/model').getHuntingHistoryOrders
  const getHuntingOngoingAmountLabel: typeof import('./pages/Delegation/model').getHuntingOngoingAmountLabel
  const getHuntingOngoingOrders: typeof import('./pages/Delegation/model').getHuntingOngoingOrders
  const getHuntingOngoingStatus: typeof import('./pages/Delegation/model').getHuntingOngoingStatus
  const getHuntingQuoteActionLabel: typeof import('./pages/Delegation/model').getHuntingQuoteActionLabel
  const getHuntingTaskAmountText: typeof import('./pages/Delegation/model').getHuntingTaskAmountText
  const getHuntingTaskPublishTimeText: typeof import('./pages/Delegation/model').getHuntingTaskPublishTimeText
  const getLatestLocalPublishInfoDraft: typeof import('./tools/publishInfo').getLatestLocalPublishInfoDraft
  const getLocalPublishInfoDrafts: typeof import('./tools/publishInfo').getLocalPublishInfoDrafts
  const getMessageToastSnapshot: typeof import('./tools/messageToast').getMessageToastSnapshot
  const getOrderModuleCounts: typeof import('./components/OrderModuleCard/model').getOrderModuleCounts
  const getProductFilterLabel: typeof import('./shared/clientPageModel').getProductFilterLabel
  const getProfileRequirement: typeof import('./shared/clientPageModel').getProfileRequirement
  const getProfileRequirementTemplate: typeof import('./shared/clientPageModel').getProfileRequirementTemplate
  const getPublishDestinationLabel: typeof import('./tools/publishInfo').getPublishDestinationLabel
  const getRecommendedHuntingTasks: typeof import('./pages/Delegation/model').getRecommendedHuntingTasks
  const getRoleHint: typeof import('./shared/clientPageModel').getRoleHint
  const getRouteForTab: typeof import('./shared/clientPageModel').getRouteForTab
  const getStoredAddressBook: typeof import('./shared/clientPageModel').getStoredAddressBook
  const getStoredClientAuthSession: typeof import('@unknown/api-client').getStoredClientAuthSession
  const getStoredPasswordCredential: typeof import('./shared/clientPageModel').getStoredPasswordCredential
  const getStoredProfileDraft: typeof import('./shared/clientPageModel').getStoredProfileDraft
  const getTabFromRoute: typeof import('./shared/clientPageModel').getTabFromRoute
  const getTabTitle: typeof import('./shared/clientPageModel').getTabTitle
  const getTutorCalendarTasks: typeof import('./tools/tutorCalendar').getTutorCalendarTasks
  const getTutorCardDataFromDraft: typeof import('./components/TutorCard/model').getTutorCardDataFromDraft
  const getTutorCardMode: typeof import('./components/TutorCard/model').getTutorCardMode
  const getTutorDateKey: typeof import('./tools/tutorCalendar').getTutorDateKey
  const getWalletDisplayDate: typeof import('./tools/wallet').getWalletDisplayDate
  const getWalletMonthKey: typeof import('./tools/wallet').getWalletMonthKey
  const getWalletMonthOptions: typeof import('./tools/wallet').getWalletMonthOptions
  const getWalletMonthlySummary: typeof import('./tools/wallet').getWalletMonthlySummary
  const getWalletTotalAmount: typeof import('./tools/wallet').getWalletTotalAmount
  const hasCounterQuoteAmount: typeof import('./pages/Delegation/model').hasCounterQuoteAmount
  const hasInvalidCounterQuoteAmount: typeof import('./pages/Delegation/model').hasInvalidCounterQuoteAmount
  const hasInvalidFields: typeof import('./tools/validation').hasInvalidFields
  const hasInvalidRequiredFields: typeof import('./tools/validation').hasInvalidRequiredFields
  const hasStoredPendingRegistration: typeof import('./shared/clientPageModel').hasStoredPendingRegistration
  const hasValidCounterQuoteAmount: typeof import('./pages/Delegation/model').hasValidCounterQuoteAmount
  const hideMessage: typeof import('./tools/messageToast').hideMessage
  const huntingCertificationStatusLabels: typeof import('./components/HuntingCertificationCard/model').huntingCertificationStatusLabels
  const isDelegationFulfillingStatus: typeof import('./pages/Delegation/model').isDelegationFulfillingStatus
  const isDelegationListVisible: typeof import('./pages/Delegation/model').isDelegationListVisible
  const isDelegationQuoteStatus: typeof import('./pages/Delegation/model').isDelegationQuoteStatus
  const isDelegationTaskLocked: typeof import('./pages/Delegation/model').isDelegationTaskLocked
  const isHuntingCancelledStatus: typeof import('./pages/Delegation/model').isHuntingCancelledStatus
  const isHuntingCompletedStatus: typeof import('./pages/Delegation/model').isHuntingCompletedStatus
  const isHuntingFulfillingStatus: typeof import('./pages/Delegation/model').isHuntingFulfillingStatus
  const isHuntingPublishedStatus: typeof import('./pages/Delegation/model').isHuntingPublishedStatus
  const isHuntingQuoteStatus: typeof import('./pages/Delegation/model').isHuntingQuoteStatus
  const isHuntingQuoteWaitingHunter: typeof import('./pages/Delegation/model').isHuntingQuoteWaitingHunter
  const isHuntingQuoteWaitingPublisher: typeof import('./pages/Delegation/model').isHuntingQuoteWaitingPublisher
  const isHuntingTaskPublishType: typeof import('./tools/publishInfo').isHuntingTaskPublishType
  const isNegotiableAmount: typeof import('./tools/publishInfo').isNegotiableAmount
  const isNegotiatingHuntingQuote: typeof import('./pages/Delegation/model').isNegotiatingHuntingQuote
  const isPositiveAmount: typeof import('./tools/publishInfo').isPositiveAmount
  const isQuoteLockedForPublisher: typeof import('./pages/Delegation/model').isQuoteLockedForPublisher
  const jobFilters: typeof import('./shared/clientPageModel').jobFilters
  const lazy: typeof import('react').lazy
  const localAuthCode: typeof import('./tools/localAuth').localAuthCode
  const localPasswordMinLength: typeof import('./tools/localAuth').localPasswordMinLength
  const memo: typeof import('react').memo
  const merchantRegistrationBusinessFields: typeof import('./shared/clientPageModel').merchantRegistrationBusinessFields
  const messageToastApi: typeof import('./tools/messageToast').messageToastApi
  const messageToastMeta: typeof import('./tools/messageToast').messageToastMeta
  const mineEntryLabels: typeof import('@unknown/domain').mineEntryLabels
  const moduleRoutePaths: typeof import('./shared/clientPageModel').moduleRoutePaths
  const normalizeAddressBookItems: typeof import('./shared/clientPageModel').normalizeAddressBookItems
  const normalizeByKey: typeof import('./tools/validation').normalizeByKey
  const parentChildInfoFields: typeof import('./shared/clientPageModel').parentChildInfoFields
  const parentRegistrationAddressFields: typeof import('./shared/clientPageModel').parentRegistrationAddressFields
  const parentRegistrationProfileTemplate: typeof import('./shared/clientPageModel').parentRegistrationProfileTemplate
  const parseTutorSubjectLevelItems: typeof import('./components/TutorCard/model').parseTutorSubjectLevelItems
  const parseTutorSubjects: typeof import('./shared/tutorModel').parseTutorSubjects
  const parseWalletBucketAmount: typeof import('./tools/wallet').parseWalletBucketAmount
  const parseWalletRecordAmount: typeof import('./tools/wallet').parseWalletRecordAmount
  const passwordCredentialStorageKey: typeof import('./shared/clientPageModel').passwordCredentialStorageKey
  const paymentMethodLabels: typeof import('@unknown/domain').paymentMethodLabels
  const pendingRegistrationStorageKey: typeof import('./shared/clientPageModel').pendingRegistrationStorageKey
  const productFilters: typeof import('./shared/clientPageModel').productFilters
  const profileDraftStorageKey: typeof import('./shared/clientPageModel').profileDraftStorageKey
  const profileDraftToClientAddressRequest: typeof import('./shared/clientPageModel').profileDraftToClientAddressRequest
  const profileRequirementTemplates: typeof import('./shared/clientPageModel').profileRequirementTemplates
  const registrationProfileTemplates: typeof import('./shared/clientPageModel').registrationProfileTemplates
  const roleLabels: typeof import('@unknown/domain').roleLabels
  const roles: typeof import('./shared/clientPageModel').roles
  const saveLocalPasswordCredential: typeof import('./tools/localAuth').saveLocalPasswordCredential
  const saveLocalPublishInfoDraft: typeof import('./tools/publishInfo').saveLocalPublishInfoDraft
  const setStoredAddressBook: typeof import('./shared/clientPageModel').setStoredAddressBook
  const setStoredClientAuthSession: typeof import('@unknown/api-client').setStoredClientAuthSession
  const setStoredPasswordCredential: typeof import('./shared/clientPageModel').setStoredPasswordCredential
  const setStoredPendingRegistration: typeof import('./shared/clientPageModel').setStoredPendingRegistration
  const setStoredProfileDraft: typeof import('./shared/clientPageModel').setStoredProfileDraft
  const showMessage: typeof import('./tools/messageToast').showMessage
  const startTransition: typeof import('react').startTransition
  const stringifyTutorSubjectLevelItems: typeof import('./components/TutorCard/model').stringifyTutorSubjectLevelItems
  const subscribeMessageToast: typeof import('./tools/messageToast').subscribeMessageToast
  const tabIcons: typeof import('./shared/clientPageModel').tabIcons
  const tutorCertificationStatusLabels: typeof import('./components/TutorCard/model').tutorCertificationStatusLabels
  const tutorGradeOptions: typeof import('./components/TutorCard/model').tutorGradeOptions
  const tutorLevelOptions: typeof import('./components/TutorCard/model').tutorLevelOptions
  const tutorSorts: typeof import('./shared/clientPageModel').tutorSorts
  const tutorSubjectOptions: typeof import('./shared/tutorModel').tutorSubjectOptions
  const use: typeof import('react').use
  const useActionState: typeof import('react').useActionState
  const useApplyTutorTrial: typeof import('@unknown/hooks').useApplyTutorTrial
  const useCallback: typeof import('react').useCallback
  const useChatConversations: typeof import('@unknown/hooks').useChatConversations
  const useChatMessages: typeof import('@unknown/hooks').useChatMessages
  const useChatQuickActions: typeof import('@unknown/hooks').useChatQuickActions
  const useClientAddresses: typeof import('@unknown/hooks').useClientAddresses
  const useClientHome: typeof import('@unknown/hooks').useClientHome
  const useClientLogin: typeof import('@unknown/hooks').useClientLogin
  const useClientRegister: typeof import('@unknown/hooks').useClientRegister
  const useClientWorkspace: typeof import('@unknown/hooks').useClientWorkspace
  const useContext: typeof import('react').useContext
  const useCreateChatConversation: typeof import('@unknown/hooks').useCreateChatConversation
  const useCreateChatQuickAction: typeof import('@unknown/hooks').useCreateChatQuickAction
  const useCreateClientAddress: typeof import('@unknown/hooks').useCreateClientAddress
  const useCreateHuntingProject: typeof import('@unknown/hooks').useCreateHuntingProject
  const useDebugValue: typeof import('react').useDebugValue
  const useDeferredValue: typeof import('react').useDeferredValue
  const useDelegationList: typeof import('./pages/Delegation/hooks/useDelegationList').useDelegationList
  const useDelegationTaskFlow: typeof import('./pages/Delegation/hooks/useDelegationTaskFlow').useDelegationTaskFlow
  const useDeleteClientAddress: typeof import('@unknown/hooks').useDeleteClientAddress
  const useEffect: typeof import('react').useEffect
  const useEffectEvent: typeof import('react').useEffectEvent
  const useGlobalStore: typeof import('./store/global').useGlobalStore
  const useGlobalUser: typeof import('./store/global').useGlobalUser
  const useHuntingTaskActions: typeof import('./pages/Delegation/hooks/useHuntingTaskActions').useHuntingTaskActions
  const useId: typeof import('react').useId
  const useImperativeHandle: typeof import('react').useImperativeHandle
  const useInsertionEffect: typeof import('react').useInsertionEffect
  const useLayoutEffect: typeof import('react').useLayoutEffect
  const useLocation: typeof import('react-router-dom').useLocation
  const useMemo: typeof import('react').useMemo
  const useNavigate: typeof import('react-router-dom').useNavigate
  const useOngoingQuoteFlow: typeof import('./pages/Delegation/hooks/useOngoingQuoteFlow').useOngoingQuoteFlow
  const useOptimistic: typeof import('react').useOptimistic
  const useProducts: typeof import('@unknown/hooks').useProducts
  const usePublishHuntingTask: typeof import('@unknown/hooks').usePublishHuntingTask
  const usePublishTutorDemand: typeof import('@unknown/hooks').usePublishTutorDemand
  const usePurchaseProduct: typeof import('@unknown/hooks').usePurchaseProduct
  const useReducer: typeof import('react').useReducer
  const useRef: typeof import('react').useRef
  const useResetClientPassword: typeof import('@unknown/hooks').useResetClientPassword
  const useSendChatMessage: typeof import('@unknown/hooks').useSendChatMessage
  const useState: typeof import('react').useState
  const useSyncExternalStore: typeof import('react').useSyncExternalStore
  const useTransition: typeof import('react').useTransition
  const useTutorTrialActions: typeof import('./pages/Tutor/hooks/useTutorTrialActions').useTutorTrialActions
  const useUpdateClientAddress: typeof import('@unknown/hooks').useUpdateClientAddress
  const useUpdateTutorExposure: typeof import('@unknown/hooks').useUpdateTutorExposure
  const useUseClientAddress: typeof import('@unknown/hooks').useUseClientAddress
  const validateByKey: typeof import('./tools/validation').validateByKey
  const verifyLocalPasswordCredential: typeof import('./tools/localAuth').verifyLocalPasswordCredential
}
// for type re-export
declare global {
  // @ts-ignore
  export type { ChatModuleProps } from './components/ChatModule/index'
  import('./components/ChatModule/index')
  // @ts-ignore
  export type { HuntingCertificationCardProps } from './components/HuntingCertificationCard/index'
  import('./components/HuntingCertificationCard/index')
  // @ts-ignore
  export type { HuntingCertificationCardMode, HuntingCertificationCardData, HuntingCertificationStatus } from './components/HuntingCertificationCard/model'
  import('./components/HuntingCertificationCard/model')
  // @ts-ignore
  export type { OrderModuleCardVariant, OrderModuleCardProps } from './components/OrderModuleCard/index'
  import('./components/OrderModuleCard/index')
  // @ts-ignore
  export type { OrderModuleCounts } from './components/OrderModuleCard/model'
  import('./components/OrderModuleCard/model')
  // @ts-ignore
  export type { PublishInfoDialogProps } from './components/PublishInfoDialog/index'
  import('./components/PublishInfoDialog/index')
  // @ts-ignore
  export type { ScrollingTickerDirection, ScrollingTickerProps } from './components/ScrollingTicker/index'
  import('./components/ScrollingTicker/index')
  // @ts-ignore
  export type { SummaryCardVariant, AccountSummaryCardProps, WalletSummaryCardProps } from './components/SummaryCards/index'
  import('./components/SummaryCards/index')
  // @ts-ignore
  export type { TutorCalendarTask, TutorCalendarDialogProps } from './components/TutorCalendar/index'
  import('./components/TutorCalendar/index')
  // @ts-ignore
  export type { TutorCardProps } from './components/TutorCard/index'
  import('./components/TutorCard/index')
  // @ts-ignore
  export type { TutorCardMode, TutorSubjectLevelItem, TutorCardData, TutorCertificationStatus } from './components/TutorCard/model'
  import('./components/TutorCard/model')
  // @ts-ignore
  export type { TutorCertificationInfoSaveMode, TutorCertificationInfoDialogProps } from './components/TutorCertificationInfoDialog/index'
  import('./components/TutorCertificationInfoDialog/index')
  // @ts-ignore
  export type { DelegationProps } from './pages/Delegation/index'
  import('./pages/Delegation/index')
  // @ts-ignore
  export type { DelegationSortMode, DelegationToolbarPanel } from './pages/Delegation/model'
  import('./pages/Delegation/model')
  // @ts-ignore
  export type { AddressEditorMode, PhoneChangeDraft, PasswordResetDraft } from './pages/Settings/components/SettingsDialogs'
  import('./pages/Settings/components/SettingsDialogs')
  // @ts-ignore
  export type { StoredPasswordCredential, PasswordCredentialStore, PendingRegistrationRecord, PendingRegistrationStore } from './shared/clientPageModel'
  import('./shared/clientPageModel')
  // @ts-ignore
  export type { GlobalUser, GlobalStoreState, GlobalStoreApi } from './store/global'
  import('./store/global')
  // @ts-ignore
  export type { PublishInfoType, DelegationAmountMode, PublishInfoDraft, LocalPublishInfoDraft } from './tools/publishInfo'
  import('./tools/publishInfo')
  // @ts-ignore
  export type { ValidationResult, ValidationContext } from './tools/validation'
  import('./tools/validation')
  // @ts-ignore
  export type { WalletMonthOption, WalletMonthlySummary } from './tools/wallet'
  import('./tools/wallet')
  // @ts-ignore
  export type { PageSurface, AuthMode, LoginCredentialMode, ProductFilter, JobFilter, TutorSort, CheckoutState } from './types/app'
  import('./types/app')
  // @ts-ignore
  export type { H5RuntimeGlobals, ApiEnvelope, PasswordResetResult, LoginProps, LoginFormProps, RegisterFormProps, LoginRegisterCardProps, PasswordResetCardProps, RegistrationGuideProps } from './types/auth'
  import('./types/auth')
  // @ts-ignore
  export type { HuntingAreaInputMode, HuntingProjectStop, HuntingProjectDraft, HuntingProject, HuntingProjectDialogProps } from './types/hunting-project'
  import('./types/hunting-project')
  // @ts-ignore
  export type { MessageToastType, MessageToastState, MessageToastOptions } from './types/message-toast'
  import('./types/message-toast')
  // @ts-ignore
  export type { ProfileRequirementField, ProfileRequirementTemplate, ProfileRequirement, ProfileDraftState, RegistrationProfileField, RegistrationProfileTemplate, RegistrationProfileDraft, AddressInfoFormMode, AddressInfoPreviewVariant, AddressBookItem, AddressInfoFormProps } from './types/profile'
  import('./types/profile')
  // @ts-ignore
  export type { ChildProfileOption, TutorTrialJob, TutorApplicationCandidate } from './types/tutor-workflow'
  import('./types/tutor-workflow')
}
