/* eslint-disable */
/* prettier-ignore */
// @ts-nocheck
// noinspection JSUnusedGlobalSymbols
// Generated by unplugin-auto-import
// biome-ignore lint: disable
export {}
declare global {
  const AccountSummaryCard: typeof import('../components/SummaryCards/index').AccountSummaryCard
  const Activity: typeof import('react').Activity
  const AddressInfoForm: typeof import('../components/AddressInfoForm/index').AddressInfoForm
  const AlertCircle: typeof import('lucide-react').AlertCircle
  const App: typeof import('@h5/App').App
  const ArrowLeft: typeof import('lucide-react').ArrowLeft
  const BadgeCheck: typeof import('lucide-react').BadgeCheck
  const BottomTabs: typeof import('../components/AppShell/index').BottomTabs
  const BriefcaseBusiness: typeof import('lucide-react').BriefcaseBusiness
  const BrowserRouter: typeof import('react-router-dom').BrowserRouter
  const CalendarClock: typeof import('lucide-react').CalendarClock
  const CheckCircle2: typeof import('lucide-react').CheckCircle2
  const CheckoutSheet: typeof import('../components/WorkflowDialogs/index').CheckoutSheet
  const ChevronRight: typeof import('lucide-react').ChevronRight
  const CircleDollarSign: typeof import('lucide-react').CircleDollarSign
  const ClipboardCheck: typeof import('lucide-react').ClipboardCheck
  const Crosshair: typeof import('lucide-react').Crosshair
  const Delegation: typeof import('../pages/Delegation/index').Delegation
  const Featured: typeof import('../pages/Featured/index').Featured
  const Fragment: typeof import('react').Fragment
  const GraduationCap: typeof import('lucide-react').GraduationCap
  const Header: typeof import('../components/AppShell/index').Header
  const Heart: typeof import('lucide-react').Heart
  const Home: typeof import('lucide-react').Home
  const HuntingCertification: typeof import('../pages/HuntingCertification/index').HuntingCertification
  const HuntingCertificationCard: typeof import('../components/HuntingCertificationCard/index').HuntingCertificationCard
  const KeyRound: typeof import('lucide-react').KeyRound
  const LogOut: typeof import('lucide-react').LogOut
  const Login: typeof import('../pages/Login/index').Login
  const LoginRegisterCard: typeof import('../components/LoginRegisterCard/index').LoginRegisterCard
  const Marketing: typeof import('../pages/Marketing/index').Marketing
  const Megaphone: typeof import('lucide-react').Megaphone
  const MerchantSales: typeof import('../pages/MerchantSales/index').MerchantSales
  const MessageCircle: typeof import('lucide-react').MessageCircle
  const MessageToast: typeof import('../components/MessageToast/index').MessageToast
  const Metric: typeof import('../components/PageWidgets/index').Metric
  const Mine: typeof import('../pages/Mine/index').Mine
  const MinePopover: typeof import('../components/AppShell/index').MinePopover
  const Navigate: typeof import('react-router-dom').Navigate
  const OngoingOrdersDialog: typeof import('../components/WorkflowDialogs/index').OngoingOrdersDialog
  const OrderModuleCard: typeof import('../components/OrderModuleCard/index').OrderModuleCard
  const Orders: typeof import('../pages/Orders/index').Orders
  const PackageCheck: typeof import('lucide-react').PackageCheck
  const PageShell: typeof import('../components/AppShell/index').PageShell
  const PartTime: typeof import('../pages/PartTime/index').PartTime
  const PartTimeJobCard: typeof import('../components/PageWidgets/index').PartTimeJobCard
  const Plus: typeof import('lucide-react').Plus
  const ProductListCard: typeof import('../components/PageWidgets/index').ProductListCard
  const ProfileCompletionDialog: typeof import('../components/WorkflowDialogs/index').ProfileCompletionDialog
  const ProfileContextCard: typeof import('../components/AppShell/index').ProfileContextCard
  const PublishInfoDialog: typeof import('../components/PublishInfoDialog/index').PublishInfoDialog
  const QueryClient: typeof import('@tanstack/react-query').QueryClient
  const QueryClientProvider: typeof import('@tanstack/react-query').QueryClientProvider
  const RegistrationProfileCompletion: typeof import('../components/RegistrationProfileCompletion/index').RegistrationProfileCompletion
  const Route: typeof import('react-router-dom').Route
  const Routes: typeof import('react-router-dom').Routes
  const ScrollingTicker: typeof import('../components/ScrollingTicker/index').ScrollingTicker
  const SectionHeader: typeof import('../components/PageWidgets/index').SectionHeader
  const Settings: typeof import('lucide-react').Settings
  const SettingsView: typeof import('../pages/Settings/index').SettingsView
  const ShieldCheck: typeof import('lucide-react').ShieldCheck
  const ShoppingBag: typeof import('lucide-react').ShoppingBag
  const Smartphone: typeof import('lucide-react').Smartphone
  const Store: typeof import('lucide-react').Store
  const StrictMode: typeof import('react').StrictMode
  const Suspense: typeof import('react').Suspense
  const Truck: typeof import('lucide-react').Truck
  const Tutor: typeof import('../pages/Tutor/index').Tutor
  const TutorCalendarDialog: typeof import('../components/TutorCalendar/index').TutorCalendarDialog
  const TutorCard: typeof import('../components/TutorCard/index').TutorCard
  const TutorCertification: typeof import('../pages/Tutor/TutorCertification').TutorCertification
  const TutorCertificationInfoDialog: typeof import('../components/TutorCertificationInfoDialog/index').TutorCertificationInfoDialog
  const UserRound: typeof import('lucide-react').UserRound
  const Wallet: typeof import('../pages/Wallet/index').Wallet
  const WalletCards: typeof import('lucide-react').WalletCards
  const WalletSummaryCard: typeof import('../components/SummaryCards/index').WalletSummaryCard
  const WorkbenchInfoCard: typeof import('../components/PageWidgets/index').WorkbenchInfoCard
  const WorkbenchQuickEntryCard: typeof import('../components/PageWidgets/index').WorkbenchQuickEntryCard
  const XCircle: typeof import('lucide-react').XCircle
  const accountStatusLabels: typeof import('@unknown/domain').accountStatusLabels
  const addressBookStorageKey: typeof import('../shared/clientPageModel').addressBookStorageKey
  const addressInfoFields: typeof import('../shared/clientPageModel').addressInfoFields
  const addressInfoTemplate: typeof import('../shared/clientPageModel').addressInfoTemplate
  const cache: typeof import('react').cache
  const cacheSignal: typeof import('react').cacheSignal
  const campusAreaOptions: typeof import('../shared/clientPageModel').campusAreaOptions
  const clearStoredClientAuthSession: typeof import('@unknown/api-client').clearStoredClientAuthSession
  const clearStoredPendingRegistration: typeof import('../shared/clientPageModel').clearStoredPendingRegistration
  const clientPrimaryTabs: typeof import('@unknown/domain').clientPrimaryTabs
  const clientPublishPlatformLabels: typeof import('@unknown/domain').clientPublishPlatformLabels
  const createAddressBookItem: typeof import('../shared/clientPageModel').createAddressBookItem
  const createContext: typeof import('react').createContext
  const createRef: typeof import('react').createRef
  const createRoot: typeof import('react-dom/client').createRoot
  const deliveryModeLabels: typeof import('@unknown/domain').deliveryModeLabels
  const filterProducts: typeof import('../shared/clientPageModel').filterProducts
  const formatCurrency: typeof import('../shared/clientPageModel').formatCurrency
  const formatTutorSubjects: typeof import('../shared/tutorModel').formatTutorSubjects
  const forwardRef: typeof import('react').forwardRef
  const getDefaultDeliveryMode: typeof import('../shared/clientPageModel').getDefaultDeliveryMode
  const getDefaultPrimaryTab: typeof import('@unknown/domain').getDefaultPrimaryTab
  const getDefaultRouteForRole: typeof import('../shared/clientPageModel').getDefaultRouteForRole
  const getDeliveryFee: typeof import('../shared/clientPageModel').getDeliveryFee
  const getErrorMessage: typeof import('../components/MessageToast/index').getErrorMessage
  const getFilledProfileDraft: typeof import('../shared/clientPageModel').getFilledProfileDraft
  const getHuntingCertificationCardMode: typeof import('../components/HuntingCertificationCard/model').getHuntingCertificationCardMode
  const getHuntingCertificationDataFromDraft: typeof import('../components/HuntingCertificationCard/model').getHuntingCertificationDataFromDraft
  const getOrderModuleCounts: typeof import('../components/OrderModuleCard/model').getOrderModuleCounts
  const getProductFilterLabel: typeof import('../shared/clientPageModel').getProductFilterLabel
  const getProfileRequirement: typeof import('../shared/clientPageModel').getProfileRequirement
  const getProfileRequirementTemplate: typeof import('../shared/clientPageModel').getProfileRequirementTemplate
  const getRoleHint: typeof import('../shared/clientPageModel').getRoleHint
  const getRouteForTab: typeof import('../shared/clientPageModel').getRouteForTab
  const getStoredAddressBook: typeof import('../shared/clientPageModel').getStoredAddressBook
  const getStoredClientAuthSession: typeof import('@unknown/api-client').getStoredClientAuthSession
  const getStoredPasswordCredential: typeof import('../shared/clientPageModel').getStoredPasswordCredential
  const getStoredProfileDraft: typeof import('../shared/clientPageModel').getStoredProfileDraft
  const getTabFromRoute: typeof import('../shared/clientPageModel').getTabFromRoute
  const getTabTitle: typeof import('../shared/clientPageModel').getTabTitle
  const getTutorCardDataFromDraft: typeof import('../components/TutorCard/model').getTutorCardDataFromDraft
  const getTutorCardMode: typeof import('../components/TutorCard/model').getTutorCardMode
  const hasStoredPendingRegistration: typeof import('../shared/clientPageModel').hasStoredPendingRegistration
  const huntingCertificationStatusLabels: typeof import('../components/HuntingCertificationCard/model').huntingCertificationStatusLabels
  const jobFilters: typeof import('../shared/clientPageModel').jobFilters
  const lazy: typeof import('react').lazy
  const memo: typeof import('react').memo
  const mineEntryLabels: typeof import('@unknown/domain').mineEntryLabels
  const moduleRoutePaths: typeof import('../shared/clientPageModel').moduleRoutePaths
  const normalizeAddressBookItems: typeof import('../shared/clientPageModel').normalizeAddressBookItems
  const parseTutorSubjectLevelItems: typeof import('../components/TutorCard/model').parseTutorSubjectLevelItems
  const parseTutorSubjects: typeof import('../shared/tutorModel').parseTutorSubjects
  const passwordCredentialStorageKey: typeof import('../shared/clientPageModel').passwordCredentialStorageKey
  const paymentMethodLabels: typeof import('@unknown/domain').paymentMethodLabels
  const pendingRegistrationStorageKey: typeof import('../shared/clientPageModel').pendingRegistrationStorageKey
  const productFilters: typeof import('../shared/clientPageModel').productFilters
  const profileDraftStorageKey: typeof import('../shared/clientPageModel').profileDraftStorageKey
  const profileRequirementTemplates: typeof import('../shared/clientPageModel').profileRequirementTemplates
  const registrationProfileTemplates: typeof import('../shared/clientPageModel').registrationProfileTemplates
  const roleLabels: typeof import('@unknown/domain').roleLabels
  const roles: typeof import('../shared/clientPageModel').roles
  const setStoredAddressBook: typeof import('../shared/clientPageModel').setStoredAddressBook
  const setStoredClientAuthSession: typeof import('@unknown/api-client').setStoredClientAuthSession
  const setStoredPasswordCredential: typeof import('../shared/clientPageModel').setStoredPasswordCredential
  const setStoredPendingRegistration: typeof import('../shared/clientPageModel').setStoredPendingRegistration
  const setStoredProfileDraft: typeof import('../shared/clientPageModel').setStoredProfileDraft
  const startTransition: typeof import('react').startTransition
  const stringifyTutorSubjectLevelItems: typeof import('../components/TutorCard/model').stringifyTutorSubjectLevelItems
  const tabIcons: typeof import('../shared/clientPageModel').tabIcons
  const tutorCertificationStatusLabels: typeof import('../components/TutorCard/model').tutorCertificationStatusLabels
  const tutorGradeOptions: typeof import('../components/TutorCard/model').tutorGradeOptions
  const tutorLevelOptions: typeof import('../components/TutorCard/model').tutorLevelOptions
  const tutorSorts: typeof import('../shared/clientPageModel').tutorSorts
  const tutorSubjectOptions: typeof import('../shared/tutorModel').tutorSubjectOptions
  const use: typeof import('react').use
  const useActionState: typeof import('react').useActionState
  const useCallback: typeof import('react').useCallback
  const useClientHome: typeof import('@unknown/hooks').useClientHome
  const useClientLogin: typeof import('@unknown/hooks').useClientLogin
  const useClientRegister: typeof import('@unknown/hooks').useClientRegister
  const useClientWorkspace: typeof import('@unknown/hooks').useClientWorkspace
  const useContext: typeof import('react').useContext
  const useDebugValue: typeof import('react').useDebugValue
  const useDeferredValue: typeof import('react').useDeferredValue
  const useEffect: typeof import('react').useEffect
  const useEffectEvent: typeof import('react').useEffectEvent
  const useId: typeof import('react').useId
  const useImperativeHandle: typeof import('react').useImperativeHandle
  const useInsertionEffect: typeof import('react').useInsertionEffect
  const useLayoutEffect: typeof import('react').useLayoutEffect
  const useLocation: typeof import('react-router-dom').useLocation
  const useMemo: typeof import('react').useMemo
  const useMessageToast: typeof import('../components/MessageToast/index').useMessageToast
  const useNavigate: typeof import('react-router-dom').useNavigate
  const useOptimistic: typeof import('react').useOptimistic
  const useProducts: typeof import('@unknown/hooks').useProducts
  const usePublishHuntingTask: typeof import('@unknown/hooks').usePublishHuntingTask
  const usePurchaseProduct: typeof import('@unknown/hooks').usePurchaseProduct
  const useReducer: typeof import('react').useReducer
  const useRef: typeof import('react').useRef
  const useState: typeof import('react').useState
  const useSyncExternalStore: typeof import('react').useSyncExternalStore
  const useTransition: typeof import('react').useTransition
}
// for type re-export
declare global {
  // @ts-ignore
  export type { HuntingCertificationCardProps } from '../components/HuntingCertificationCard/index'
  import('../components/HuntingCertificationCard/index')
  // @ts-ignore
  export type { HuntingCertificationStatus, HuntingCertificationCardMode, HuntingCertificationCardData } from '../components/HuntingCertificationCard/model'
  import('../components/HuntingCertificationCard/model')
  // @ts-ignore
  export type { OrderModuleCardVariant, OrderModuleCardProps } from '../components/OrderModuleCard/index'
  import('../components/OrderModuleCard/index')
  // @ts-ignore
  export type { OrderModuleCounts } from '../components/OrderModuleCard/model'
  import('../components/OrderModuleCard/model')
  // @ts-ignore
  export type { PublishInfoDialogProps } from '../components/PublishInfoDialog/index'
  import('../components/PublishInfoDialog/index')
  // @ts-ignore
  export type { ScrollingTickerDirection, ScrollingTickerProps } from '../components/ScrollingTicker/index'
  import('../components/ScrollingTicker/index')
  // @ts-ignore
  export type { SummaryCardVariant, AccountSummaryCardProps, WalletSummaryCardProps } from '../components/SummaryCards/index'
  import('../components/SummaryCards/index')
  // @ts-ignore
  export type { TutorCalendarTask, TutorCalendarDialogProps } from '../components/TutorCalendar/index'
  import('../components/TutorCalendar/index')
  // @ts-ignore
  export type { TutorCardProps } from '../components/TutorCard/index'
  import('../components/TutorCard/index')
  // @ts-ignore
  export type { TutorCardMode, TutorSubjectLevelItem, TutorCardData, TutorCertificationStatus } from '../components/TutorCard/model'
  import('../components/TutorCard/model')
  // @ts-ignore
  export type { TutorCertificationInfoSaveMode, TutorCertificationInfoDialogProps } from '../components/TutorCertificationInfoDialog/index'
  import('../components/TutorCertificationInfoDialog/index')
  // @ts-ignore
  export type { DelegationProps } from '../pages/Delegation/index'
  import('../pages/Delegation/index')
  // @ts-ignore
  export type { StoredPasswordCredential, PasswordCredentialStore, PendingRegistrationRecord, PendingRegistrationStore } from '../shared/clientPageModel'
  import('../shared/clientPageModel')
}
